apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: devboard
  labels:
    app: frontend-devboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-devboard
  template:
    metadata:
      labels:
        app: frontend-devboard
    spec:
      containers:
      - name: frontend
        image: fahadjaseem/frontend-devboard:v1 
        ports:
        - containerPort: 4173


