kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: devboard
  labels:
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres 
