apiVersion: apps/v1
kind: Deployment
metadata:
  name: devboard-pod
  namespace: devboard
  labels:
    app: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: devboard-configmap

          - secretRef:
              name: secret-devboard

        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data

        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - pg_isready -U $POSTGRES_USER -d $POSTGRES_DB

          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
